# ama-bot-website-ci.yml
# 一个workflow，名字为CI
name: ama-bot-website-ci

# 触发 workflow 的事件，当有新push或者pr时执行
on:
  push:
    branches: 
      - dev
# 一个workflow由执行的一项或多项job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          pnpm install
          pnpm build
      - name: Log in to Docker Hub #登陆docker
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  #docker的用户名
          password: ${{ secrets.DOCKER_PASSWORD }}	#docker的密码

      - name: Extract metadata (tags, labels) for Docker # 获取元数据包括tag和labels
        id: meta
        uses: docker/metadata-action@latest
        with:
          images: robinfc/ama-bot-website

      - name: Build and push Docker image  #构建和发布 docker镜像
        uses: docker/build-push-action@latest
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}  #上一步所拿到的tags，默认是分支名字
          labels: ${{ steps.meta.outputs.labels }} # 上一步所拿到的labels

      # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
      - name: ssh docker login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_NAME }}
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}
          script: cd ~ && sh deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}